import React from 'react';
import { RiskScore } from './components/RiskScore';
import { DocumentSummary } from './components/DocumentSummary';
import './index.css';

function App() {
  const [loading, setLoading] = React.useState(false);

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-2xl mx-auto p-6">
        <header className="mb-6">
          <h1 className="text-3xl font-bold text-gray-900">Click-Wise</h1>
          <p className="text-gray-600 text-sm">AI-powered legal document analysis</p>
        </header>

        <div className="space-y-6">
          <RiskScore
            score={42}
            level="medium"
            flags={[
              {
                code: 'FLAG_AUTO_RENEWAL',
                description: 'Auto-renewal without explicit email notice',
                weight: 15,
              },
              {
                code: 'FLAG_DATA_SELLING',
                description: 'Selling/sharing personal data with 3rd-party brokers',
                weight: 25,
              },
            ]}
          />

          <DocumentSummary
            domain="example.com"
            docType="terms of service"
            summary={{
              executive_summary:
                'This is a placeholder summary for Phase 1. In production, this would be generated by Claude API.',
              key_clauses: [
                'Automatically renewing subscription with 30-day cancellation notice',
                'Data shared with third-party analytics providers',
                'User content licensed royalty-free for platform use',
              ],
              user_rights: [
                'Right to request data export within 30 days',
                'Right to delete account and associated data',
                'Right to opt-out of marketing emails',
              ],
              user_responsibilities: [
                'Must maintain accurate account information',
                'Responsible for account security',
                'Cannot use service for illegal purposes',
              ],
            }}
            loading={loading}
          />

          <div className="bg-gray-100 rounded-lg p-4 text-center">
            <p className="text-sm text-gray-600">
              ⚠️ This is not legal advice. This analysis is provided for informational
              purposes only. Consult a lawyer for legal matters.
            </p>
          </div>

          <button
            onClick={() => setLoading(true)}
            className="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 transition-colors font-medium"
          >
            Analyze Document
          </button>
        </div>
      </div>
    </div>
  );
}

export default App;
